version: "3.4"

# Production environment override
services:
  php:
    environment:
      APP_ENV: prod
      APP_SECRET: ${APP_SECRET}
      MERCURE_JWT_SECRET: ${CADDY_MERCURE_JWT_SECRET}
      MERCURE_URL: ${CADDY_MERCURE_URL:-https://devtest.griggsdevelopment.com/.well-known/mercure}
      MERCURE_PUBLIC_URL: https://${SERVER_NAME:-https://devtest.griggsdevelopment.com}/.well-known/mercure

  caddy:
    environment:
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
